Register new contexts, fix ed25519 context links.
digitalbazaar/cbor-ld-spec pull request #6
Opened 2021-04-16 22:53 UTC by dmitrizagidulin

2021-04-16 23:03 UTC, dlongley approved these changes
Rubberstamping ... didn't double check the exact registry values.

2021-04-18 02:26 UTC, msporny requested changes
Cross-checking against https://github.com/perma-id/w3id.org/blob/master/security/.htaccess#L34-L39 shows some discrepancies.

2021-04-18 02:26 UTC, msporny commented on index.html
> +          <td><code>https://w3id.org/security/ed25519-2018/v1</code></td>
```suggestion
          <td><code>https://w3id.org/security/suites/ed25519-2018/v1</code></td>
```

2021-04-18 02:26 UTC, msporny commented on index.html
> +          <td><code>https://w3id.org/security/ed25519-2020/v1</code></td>
```suggestion
          <td><code>https://w3id.org/security/suites/ed25519-2020/v1</code></td>
```

2021-04-21 21:52 UTC, merged